#################################################################################
# Copyright (c) 2014-2019 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# Note: while version 3.7 is technically compatible with Docker 18.06 and
# higher, this project was tested with only Docker 18.09 as of 2019-08-06.
#
################################################################################

version: "3.7"

services:
  debug:
    volumes:
      - logging-sandbox-cdh:/debug/sandbox-cdh

  fusion-livehive-proxy-sandbox-cdh:
    image: wandisco/fusion-livehive-proxy-cdh-5.16.0:7.1.0.2-3860
    depends_on:
      - fusion-server-sandbox-cdh
    networks:
      - fusion
    env_file:
      - "zone_a.env"
    ports:
      - 9083:9083
    volumes:
      - logging-sandbox-cdh:/var/log/fusion
      - fusion-sandbox-cdh-etc-wandisco:/etc/wandisco
      - fusion-sandbox-cdh-etc-hadoop:/etc/hadoop


networks:
  # One Docker network is shared between both zones
  fusion:

volumes:
  logging-sandbox-cdh:
  fusion-sandbox-cdh-etc-hadoop:
  fusion-sandbox-cdh-etc-wandisco:


